### PR TITLE
Install additional packages for F23

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by mmilata** [comment]
Thanks for the PR! I've got two questions: What component needs openssl for validating (which?) cert? And do we still need the `yum-utils` package if we install everthing through the `{{ ansible_pkg_mgr }}` method?

**Comment by vrutkovs** [comment]
> What component needs openssl for validating (which?) cert?

That happened somewhere on openshift side, probably it belongs there. I used a blank F23 cloud image, but cannot reproduce it anymore

> And do we still need the yum-utils package if we install everthing through the {{ ansible_pkg_mgr }} method?

Yep,this package seems to contain python bindings, I'll try to double-check on a clean install, however it doesn't seem to hurt for other systems

**Comment by mmilata** [comment]
> Yep,this package seems to contain python bindings, I'll try to double-check on a clean install, however it doesn't seem to hurt for other systems

Python bindings for yum? What uses them, ansible?

**Comment by vrutkovs** [comment]
> Python bindings for yum? What uses them, ansible?

Right, those are required to install `python-dnf`, however one cannot use `yum` tasks to install it :) 

I worked around it in 0051eb6, which is a bit ugly. Probably we should specify that the host should already have `yum-utils` or `python-dnf` installed instead (those are not included in default F23 Cloud I tried on)

**Comment by mmilata** [comment]
LGTM, merged. Feel free to ping me next time I forget your pull request:/

**Pull request merged**
